In [1]:
import numpy as np

In [ ]:
# Create a numpy array of even integers from 20 to 40 using various functions (i) array (ii) linspace (iii) arange

In [2]:
ar1 = np.array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])
print(ar1)

[20 22 24 26 28 30 32 34 36 38 40]


In [3]:
ar1 = np.linspace(20,40,11)
print(ar1)

[20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40.]


In [4]:
ar1 = np.arange(20,41,2)
print(ar1)

[20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
# Set the second element(index = 1) of ar1 to 0 and print the array.

In [5]:
ar1[1] = 0
print(ar1)

[20  0 24 26 28 30 32 34 36 38 40]


In [ ]:
# Print the data type of the elements of ar1 using the ‘dtype’ command.

In [6]:
print(np.dtype(ar1[0]))
print(np.dtype(ar1[1]))
print(np.dtype(ar1[2]))
print(np.dtype(ar1[3]))
print(np.dtype(ar1[4]))
print(np.dtype(ar1[5]))

int64
int64
int64
int64
int64
int64


In [ ]:
# Use the ‘any’ function to check if any of the elements in ar1 are zero or not.

In [7]:
np.any(ar1)

True

In [8]:
np.all(ar1)

False

In [ ]:
# Print the length and dimension of ar1 using built-in functions.

In [9]:
len(ar1)

11

In [10]:
np.ndim(ar1)

1

In [ ]:
# Statistics using numpy:

In [ ]:
# Print the largest and smallest value from ar1 using built-in functions.

In [11]:
ar1.max()

40

In [12]:
ar1.min()

0

In [ ]:
# Print mean and median of ar1 using ‘mean’ and ‘median’ functions respectively.

In [13]:
np.mean(ar1)

28.0

In [14]:
np.median(ar1)

30.0

In [ ]:
# Print standard deviation and variance of ar1 using built-in functions.

In [15]:
np.std(ar1)

10.583005244258363

In [16]:
np.var(ar1)

112.0

In [ ]:
# Print the sum and product of all elements of ar1 using the built-in functions.

In [17]:
np.sum(ar1)

308

In [18]:
np.product(ar1)

0

In [ ]:
# Other operations:

In [ ]:
# Sort ar1 in ascending order using the ‘sort’ function.

In [19]:
np.sort(ar1)

array([ 0, 20, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
# Reverse and print the ar1 using the ‘flip’ function.

In [20]:
np.flip(ar1)

array([40, 38, 36, 34, 32, 30, 28, 26, 24,  0, 20])

In [ ]:
# Count the number of non-zero elements in ar1 using ‘count_nonzero’ function.

In [21]:
np.count_nonzero(ar1)

10

In [ ]:
# Vectorization

In [ ]:
# Create and store a vector F = [32, 38, 40, 28, 56, 65, 70] which contains temperatures(Fahrenheit). Print F.

In [22]:
F = np.array([32, 38, 40, 28, 56, 65, 70])
print(F)

[32 38 40 28 56 65 70]


In [23]:
# Use the formula C/5 = (F −32)/9 to create an array C of temperatures(Centigrade) corresponding to F. Print C.
C = (5 * (F - 32)) // 9
print(C)

[ 0  3  4 -3 13 18 21]


In [ ]:
# Square every element of F and print the array.

In [24]:
np.square(ar1)

array([ 400,    0,  576,  676,  784,  900, 1024, 1156, 1296, 1444, 1600])

In [ ]:
# Find Sin, Cos and Tan of each element in F. Print the results.

In [25]:
# Convert each of the values to radians using built-in function
c1 = np.sin(np.radians(F))
c2 = np.cos(np.radians(F))
c3 = np.tan(np.radians(F))

In [26]:
print(c1, "\n")
print(c2, "\n")
print(c3, "\n")

[0.52991926 0.61566148 0.64278761 0.46947156 0.82903757 0.90630779
 0.93969262] 

[0.8480481  0.78801075 0.76604444 0.88294759 0.5591929  0.42261826
 0.34202014] 

[0.62486935 0.78128563 0.83909963 0.53170943 1.48256097 2.14450692
 2.74747742] 



In [ ]:
# Operations on a vector using relational and logical operators:

In [ ]:
# Print elements of array F which are greater than 50.

In [28]:
F>50

array([False, False, False, False,  True,  True,  True])

In [27]:
F[F>50]

array([56, 65, 70])

In [ ]:
# Print elements of array F which are divisible by both 8 and 4.

In [29]:
F[np.logical_and(F % 8 == 0, F % 4 == 0)]

array([32, 40, 56])

In [ ]:
# Print elements of array F which are divisible by 8 or 4.

In [30]:
F[np.logical_or(F % 8 == 0, F % 4 == 0)]

array([32, 40, 28, 56])

In [ ]:
# Print elements of array F which are not divisible by 4.

In [31]:
F[F % 4 != 0]

array([38, 65, 70])