In [1]:
import numpy as np

In [ ]:
# Create the matrices

In [ ]:
# Using matrix function

In [2]:
a1 = np.matrix([[5, 0, 4], [2, 3, 2], [1, 2, 1]])
print(a1)

[[5 0 4]
 [2 3 2]
 [1 2 1]]


In [3]:
b1 = np.matrix([[0, 1, 2], [1, 2, 3], [3, 1, 1]])
print(b1)

[[0 1 2]
 [1 2 3]
 [3 1 1]]


In [4]:
c1 = np.matrix([[1, 2], [3, 4], [5, 6]])
print(c1)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Using array function

In [5]:
a = np.array([[5, 0, 4], [2, 3, 2], [1, 2, 1]])
print(a)

[[5 0 4]
 [2 3 2]
 [1 2 1]]


In [6]:
b = np.array([[0, 1, 2], [1, 2, 3], [3, 1, 1]])
print(b)

[[0 1 2]
 [1 2 3]
 [3 1 1]]


In [15]:
c = np.array([[1, 2], [3, 4], [5, 6]])
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Print A * B and A1 * B1.

In [8]:
print(a * b)

[[0 0 8]
 [2 6 6]
 [3 2 1]]


In [9]:
print(a1 * b1)

[[12  9 14]
 [ 9 10 15]
 [ 5  6  9]]


In [ ]:
# Print the dimension of A, B and C using the ‘ndim’ attribute.

In [ ]:
np.ndim(a)

In [ ]:
np.ndim(b)

In [ ]:
np.ndim(c)

In [ ]:
# Print the number of rows and columns in A, B and C using the ‘shape’ attribute.

In [11]:
np.shape(a)

(3, 3)

In [10]:
type(np.shape(a))

tuple

In [17]:
print("Number of rows in a:", np.shape(a)[0])
print("Number of columns in a:", np.shape(a)[1])

Number of rows in a: 3
Number of columns in a: 3


In [18]:
print("Number of rows in b:", np.shape(b)[0])
print("Number of columns in b:", np.shape(b)[1])

Number of rows in b: 3
Number of columns in b: 3


In [19]:
print("Number of rows in c:", np.shape(c)[0])
print("Number of columns in c:", np.shape(c)[1])

Number of rows in c: 3
Number of columns in c: 2


In [ ]:
# Print the transpose of A, B and C using the ‘transpose’ function.

In [20]:
np.transpose(a)

array([[5, 2, 1],
       [0, 3, 2],
       [4, 2, 1]])

In [21]:
np.transpose(b)

array([[0, 1, 3],
       [1, 2, 1],
       [2, 3, 1]])

In [22]:
np.transpose(c)

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
# Print the diagonal of A and B using the ‘diagonal’ function.

In [23]:
np.diagonal(a)

array([5, 3, 1])

In [24]:
np.diagonal(b)

array([0, 2, 1])

In [ ]:
# Print A + B and A − B.

In [25]:
print(a + b)

[[5 1 6]
 [3 5 5]
 [4 3 2]]


In [26]:
print(a - b)

[[ 5 -1  2]
 [ 1  1 -1]
 [-2  1  0]]


In [ ]:
# Create an identity matrix of order 3 X 3 and verify that AI = A. Use ‘eye’ function.

In [27]:
i = np.eye(3, dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [28]:
np.dot(a, i)

array([[5, 0, 4],
       [2, 3, 2],
       [1, 2, 1]])

In [ ]:
# Print the matrix products AB, BA, AC and BC.

In [29]:
a * b

array([[0, 0, 8],
       [2, 6, 6],
       [3, 2, 1]])

In [30]:
b * a

array([[0, 0, 8],
       [2, 6, 6],
       [3, 2, 1]])

In [31]:
a * c

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [32]:
b * c

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [ ]:
# Verify that matrix products are computed using ‘np.dot’ function.

In [33]:
np.dot(a, b)

array([[12,  9, 14],
       [ 9, 10, 15],
       [ 5,  6,  9]])

In [34]:
np.dot(b, a)

array([[ 4,  7,  4],
       [12, 12, 11],
       [18,  5, 15]])

In [35]:
np.dot(a, c)

array([[25, 34],
       [21, 28],
       [12, 16]])

In [36]:
np.dot(b, c)

array([[13, 16],
       [22, 28],
       [11, 16]])

In [ ]:
# Print greatest and least elements of A, B and C using ‘min’ and ‘max’ functions respectively.

In [37]:
print("The minimum value in a is:", np.min(a))
print("The maximum value in a is", np.max(a))

The minimum value in a is: 0
The maximum value in a is 5


In [38]:
print("The minimum value in b is:", np.min(b))
print("The maximum value in b is:", np.max(b))

The minimum value in b is: 0
The maximum value in b is: 3


In [39]:
print("The minimum value in c is:", np.min(c))
print("The maximum value in c is:", np.max(c))

The minimum value in c is: 1
The maximum value in c is: 6


In [ ]:
# Print the sum of all elements in matrices A, B and C using the ‘sum’ function.

In [40]:
np.sum(a)

20

In [41]:
np.sum(b)

14

In [42]:
np.sum(c)

21

In [ ]:
# Print the traces of matrices A, B and C using the ‘trace’ function.

In [43]:
np.trace(a)

9

In [44]:
np.trace(b)

3

In [52]:
np.trace(c)

5

In [ ]:
# Print the flattened one-dimensional array for A, B and C using the ‘flatten’ function.

In [46]:
a.flatten()

array([5, 0, 4, 2, 3, 2, 1, 2, 1])

In [47]:
b.flatten()

array([0, 1, 2, 1, 2, 3, 3, 1, 1])

In [48]:
c.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Print the sum of rows and sum of columns for all matrices A, B and C using the ‘sum’ function. 
# [Hint: Use axis = 0 and axis = 1]

In [49]:
print("The sum of rows of a:", np.sum(a, axis=1))
print("The sum of coumns of a:", np.sum(a, axis=0))

The sum of rows of a: [9 7 4]
The sum of coumns of a: [8 5 7]


In [50]:
print("The sum of rows of b:", np.sum(b, axis=1))
print("The sum of coumns of b:", np.sum(b, axis=0))

The sum of rows of b: [3 6 5]
The sum of coumns of b: [4 4 6]


In [51]:
print("The sum of rows of c:", np.sum(a, axis=1))
print("The sum of coumns of c:", np.sum(a, axis=0))

The sum of rows of c: [9 7 4]
The sum of coumns of c: [8 5 7]
