In [1]:
import numpy as np

In [2]:
# Using the ‘array ’ function in numpy, create and print the coefficient matrix A and the right hand side vector b.

In [3]:
a = np.array([[5, 0, 4], [2, 3, 2], [1, 2, 1]])
print(a)

[[5 0 4]
 [2 3 2]
 [1 2 1]]


In [4]:
b = np.array([[1], [2], [3]])
print(b)

[[1]
 [2]
 [3]]


In [5]:
# Print the determinant of A using the ‘linalg.det’ function. If the determinant is nonzero 
# hence a unique solution for the above equation exists.

In [6]:
np.linalg.det(a)

-0.9999999999999996

In [7]:
# Print and store the solution x1 found using the ‘linalg.solve’ function.
# Verify using np.dot(A, x1) to confirm if x1 is a solution.

In [8]:
x1 = np.linalg.solve(a, b)
print(x1)

[[ 21.]
 [  4.]
 [-26.]]


In [9]:
# Verification
v = np.dot(a, x1)
print(v)

[[1.]
 [2.]
 [3.]]


In [ ]:
# We can also compute the solution x2 by computing the inverse of A.
# Verify using np.dot(A, x2) to confirm if x2 is a solution.

In [11]:
aInv = np.linalg.inv(a)
print(aInv)

[[ 1.00000000e+00 -8.00000000e+00  1.20000000e+01]
 [-7.40148683e-18 -1.00000000e+00  2.00000000e+00]
 [-1.00000000e+00  1.00000000e+01 -1.50000000e+01]]


In [12]:
x2 = np.dot(aInv, b)
print(x2)

[[ 21.]
 [  4.]
 [-26.]]


In [ ]:
# Verification

In [13]:
v = np.dot(a, x2)
print(v)

[[1.]
 [2.]
 [3.]]


In [ ]:
# We can also compute the solution x3 by computing the QR factorization of A.
# Verify using np.dot(A, x3) to confirm if x3 is a solution.

In [14]:
q, r = np.linalg.qr(a)

In [15]:
print(q)

[[-0.91287093  0.40447396  0.05538488]
 [-0.36514837 -0.74827682 -0.55384878]
 [-0.18257419 -0.52581614  0.83077316]]


In [16]:
print(r)

[[-5.47722558 -1.46059349 -4.56435465]
 [ 0.         -3.29646275 -0.40447396]
 [ 0.          0.         -0.05538488]]


In [18]:
# Find the tranpose of q
qT = np.transpose(q)

In [19]:
# Create b1 that contains the value for qT.b
b1 = np.dot(qT, b)

In [20]:
# Solve using r and b1
x3 =np.linalg.solve(r, b1)
print(x3)

[[ 21.]
 [  4.]
 [-26.]]


In [ ]:
# Verification

In [21]:
v = np.dot(a, x3)
print(v)

[[1.]
 [2.]
 [3.]]


In [ ]:
# In this exercise we will see one of the reasons why it is a bad practice to compute the inverse of a matrix 
# in general. 

In [23]:
m = np.array([[2, -1, 0, 0, 0, 0, 0],[-1, 2, -1, 0, 0, 0, 0],[0,-1, 2, -1, 0, 0, 0], [0, 0, -1, 2, -1, 0, 0], [0, 0, 0, -1, 2, -1, 0], [0, 0, 0, 0, -1, 2, -1], [0, 0, 0, 0, 0, -1, 2]])
print(m)

[[ 2 -1  0  0  0  0  0]
 [-1  2 -1  0  0  0  0]
 [ 0 -1  2 -1  0  0  0]
 [ 0  0 -1  2 -1  0  0]
 [ 0  0  0 -1  2 -1  0]
 [ 0  0  0  0 -1  2 -1]
 [ 0  0  0  0  0 -1  2]]


In [24]:
# Create and display the inverse matrix.
mInv = np.linalg.inv(m)
print(mInv)

[[0.875 0.75  0.625 0.5   0.375 0.25  0.125]
 [0.75  1.5   1.25  1.    0.75  0.5   0.25 ]
 [0.625 1.25  1.875 1.5   1.125 0.75  0.375]
 [0.5   1.    1.5   2.    1.5   1.    0.5  ]
 [0.375 0.75  1.125 1.5   1.875 1.25  0.625]
 [0.25  0.5   0.75  1.    1.25  1.5   0.75 ]
 [0.125 0.25  0.375 0.5   0.625 0.75  0.875]]


In [ ]:
# Find the pseudo inverse for a given matrix. This can be done usin ‘linalg.pinv ’ function.

In [25]:
q = np.array([[1, 2], [3, 4], [5, 6]])
print(q)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
qPinv = np.linalg.pinv(q)
print(qPinv)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [27]:
# Verify by using the dot product 
r = np.dot(qPinv, q)
print(r)

[[ 1.00000000e+00 -8.88178420e-16]
 [ 1.77635684e-15  1.00000000e+00]]


In [ ]:
# Print the 1,2 Frobenius norm of matrix A using an built-in function.

In [28]:
np.linalg.norm(a, 1)

8.0

In [29]:
np.linalg.norm(a, 2)

7.3484978647418115

In [30]:
np.linalg.norm(a, 'fro')

8.0

In [ ]:
# Print the eigen values and eigen vectors of A using built-in function.

In [31]:
egVal, egVec = np.linalg.eigh(a)

In [32]:
egVal

array([-0.24581024,  2.36491112,  6.88089912])

In [33]:
egVec

array([[ 0.04844347, -0.64249075, -0.76476066],
       [-0.54543773,  0.62440251, -0.55912359],
       [ 0.83675021,  0.4442152 , -0.32019047]])

In [ ]:
# Compute the singular value decomposition of A using built-in function.

In [34]:
s1, s2, s3 = np.linalg.svd(a)

In [35]:
print(s1)

[[-0.83986771  0.53944028  0.06021968]
 [-0.47805672 -0.68259306 -0.55274631]
 [-0.25706809 -0.4930222   0.83117092]]


In [36]:
print(s2)

[7.34849786 3.16191823 0.04303787]


In [37]:
print(s3)

[[-0.73654782 -0.26512988 -0.62225675]
 [ 0.26534307 -0.95948832  0.09473768]
 [ 0.62216587  0.09533268 -0.7770594 ]]
