In [ ]:
import time

l = []
a = time.time()
for i in range(0, 100):
    l.append(i)
    
    
b = time.time()

c = b - a

print("End time \n", b)
print("Start time \n", a)
print("Execution time \n", c)

In [1]:
import numpy as np
a = np.array([[5, 0, 4], [2, 3, 2], [1, 2, 1]])
print(a)

[[5 0 4]
 [2 3 2]
 [1 2 1]]


In [2]:
a.trace()

9

In [4]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
b.trace(offset=-2)

5

In [ ]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(c)

In [ ]:
c.trace(offset=-1)